<?php
/**
 * Sanskar AI - Community Festival Service
 * ========================================
 * Provides upcoming festival data based on user's community.
 * Static festival metadata (names, icons, significance) + 
 * AI-generated dates that are cached per community per year.
 * Works for ANY year — does not rely on hardcoded dates.
 */

namespace App\Services;

class CommunityFestivalService
{
    /**
     * Get upcoming festivals for a community (max $limit, sorted by date)
     * Dates are generated by AI and cached per community per year.
     */
    public static function getUpcomingForCommunity(string $community, int $limit = 5): array
    {
        $community = strtolower(trim($community));
        $communityKey = self::resolveCommunityKey($community);
        $year = (int) date('Y');

        // Get static festival list for this community
        $staticFestivals = self::festivalMeta()[$communityKey] ?? self::festivalMeta()['hindu'];

        // Get AI-generated dates (cached)
        $dates = self::getCachedDates($communityKey, $year);

        // Merge dates into static data
        $festivals = [];
        foreach ($staticFestivals as $fest) {
            $festName = $fest['name'];
            $dateKey = self::normalizeKey($festName);
            $date = $dates[$dateKey] ?? null;

            // Also check next year's cache for festivals that might be early next year
            if (!$date) {
                $nextYearDates = self::getCachedDates($communityKey, $year + 1);
                $date = $nextYearDates[$dateKey] ?? null;
            }

            if ($date) {
                $fest['date'] = $date;
                $festivals[] = $fest;
            }
        }

        // Filter to upcoming only (today or future)
        $today = date('Y-m-d');
        $upcoming = array_filter($festivals, fn($f) => $f['date'] >= $today);

        // Sort by date
        usort($upcoming, fn($a, $b) => strcmp($a['date'], $b['date']));

        return array_slice(array_values($upcoming), 0, $limit);
    }

    /**
     * Get the community display label
     */
    public static function getCommunityLabel(string $community): string
    {
        $community = strtolower(trim($community));
        $labels = [
            'marathi brahmin' => 'Marathi Brahmin',
            'marathi' => 'Marathi',
            'gujarati' => 'Gujarati',
            'tamil brahmin' => 'Tamil Brahmin',
            'tamil' => 'Tamil',
            'bengali' => 'Bengali',
            'punjabi' => 'Punjabi',
            'south indian' => 'South Indian',
            'north indian' => 'North Indian',
            'malayali' => 'Malayali',
            'kannada' => 'Kannada',
            'telugu' => 'Telugu',
            'odia' => 'Odia',
            'bihari' => 'Bihari',
            'rajasthani' => 'Rajasthani',
            'kashmiri' => 'Kashmiri',
        ];

        foreach ($labels as $key => $label) {
            if (strpos($community, $key) !== false) {
                return $label;
            }
        }

        return ucwords($community) ?: 'Hindu';
    }

    // ====================================================================
    // AI DATE GENERATION + FILE CACHE
    // ====================================================================

    /**
     * Get cached dates for a community and year.
     * If cache doesn't exist, generate via AI and save.
     */
    private static function getCachedDates(string $communityKey, int $year): array
    {
        $cacheDir = self::cacheDir();
        $cacheFile = $cacheDir . "/{$communityKey}_{$year}.json";

        // Check cache
        if (file_exists($cacheFile)) {
            $cached = json_decode(file_get_contents($cacheFile), true);
            if ($cached && !empty($cached)) {
                return $cached;
            }
        }

        // Generate via AI
        $dates = self::generateDatesFromAI($communityKey, $year);

        if (!empty($dates)) {
            // Ensure cache directory exists
            if (!is_dir($cacheDir)) {
                mkdir($cacheDir, 0755, true);
            }
            file_put_contents($cacheFile, json_encode($dates, JSON_PRETTY_PRINT));
        }

        return $dates;
    }

    /**
     * Call AI to generate festival dates for a community and year
     */
    private static function generateDatesFromAI(string $communityKey, int $year): array
    {
        $staticFestivals = self::festivalMeta()[$communityKey] ?? self::festivalMeta()['hindu'];
        $festivalNames = array_map(fn($f) => $f['name'], $staticFestivals);
        $namesList = implode(', ', $festivalNames);

        $communityLabel = ucwords(str_replace('_', ' ', $communityKey));
        if ($communityKey === 'hindu') {
            $communityLabel = 'Hindu (General)';
        }

        $prompt = "You are a Hindu calendar expert. For the year {$year}, provide the exact Gregorian calendar dates for these {$communityLabel} festivals:

{$namesList}

IMPORTANT RULES:
1. Hindu festivals follow the LUNAR calendar. Dates change every year. Provide ACCURATE dates for {$year} specifically.
2. Use the North Indian Purnimant calendar system for North/general Hindu festivals.
3. For Marathi/Gujarati use Amant calendar system where applicable.
4. For festivals that span multiple days (like Navratri, Durga Puja), provide the START date.
5. If a festival date falls in January of the NEXT year (e.g. Makar Sankranti, Pongal, Lohri), use the next year's date.

OUTPUT FORMAT — Return ONLY valid JSON, no other text:
{
    \"festival_name_in_lowercase_with_underscores\": \"YYYY-MM-DD\",
    \"another_festival\": \"YYYY-MM-DD\"
}

Use these exact keys (lowercase, underscores for spaces, remove parenthetical text):
" . implode("\n", array_map(fn($n) => "- \"" . self::normalizeKey($n) . "\" for \"{$n}\"", $festivalNames));

        try {
            $aiService = new AIService();
            // Use reflection or direct call to get response
            $response = self::callAIForDates($aiService, $prompt);

            if ($response) {
                // Parse JSON response
                $parsed = json_decode($response, true);
                if ($parsed && is_array($parsed)) {
                    // Validate dates
                    $validDates = [];
                    foreach ($parsed as $key => $date) {
                        if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $date)) {
                            $validDates[$key] = $date;
                        }
                    }
                    return $validDates;
                }
            }
        } catch (\Exception $e) {
            error_log("CommunityFestivalService AI date generation failed: " . $e->getMessage());
        }

        // Fallback: return empty — festivals won't have dates
        return [];
    }

    /**
     * Call AIService to get festival dates
     */
    private static function callAIForDates(AIService $aiService, string $prompt): ?string
    {
        // Build the OpenAI request directly since we need JSON response
        $apiKey = getenv('AI_API_KEY') ?: '';
        $model = getenv('AI_MODEL') ?: 'gpt-4o-mini';

        if (empty($apiKey)) {
            return null;
        }

        $data = [
            'model' => $model,
            'messages' => [
                ['role' => 'system', 'content' => 'You are a Hindu calendar expert. Return ONLY valid JSON with festival dates. No explanations.'],
                ['role' => 'user', 'content' => $prompt],
            ],
            'temperature' => 0.2,
            'max_tokens' => 1500,
            'response_format' => ['type' => 'json_object'],
        ];

        set_time_limit(60);

        $ch = curl_init('https://api.openai.com/v1/chat/completions');
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_POST => true,
            CURLOPT_HTTPHEADER => [
                'Content-Type: application/json',
                'Authorization: Bearer ' . $apiKey,
            ],
            CURLOPT_POSTFIELDS => json_encode($data),
            CURLOPT_TIMEOUT => 45,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => 0,
        ]);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        if ($httpCode !== 200 || !$response) {
            return null;
        }

        $result = json_decode($response, true);
        return $result['choices'][0]['message']['content'] ?? null;
    }

    /**
     * Get cache directory path
     */
    private static function cacheDir(): string
    {
        // Store cache relative to the project root
        $root = dirname(dirname(__DIR__)); // Go up from app/services to project root
        return $root . '/storage/cache/festivals';
    }

    /**
     * Normalize a festival name to a cache key
     */
    private static function normalizeKey(string $name): string
    {
        // Remove parenthetical text
        $name = preg_replace('/\s*\([^)]*\)/', '', $name);
        // Replace non-alphanumeric with underscores
        $name = preg_replace('/[^a-zA-Z0-9]+/', '_', strtolower(trim($name)));
        // Remove trailing underscore
        return rtrim($name, '_');
    }

    /**
     * Resolve community input to a key in festivalMeta
     */
    private static function resolveCommunityKey(string $community): string
    {
        foreach (self::communityKeywords() as $key => $keywords) {
            foreach ($keywords as $kw) {
                if (strpos($community, $kw) !== false) {
                    return $key;
                }
            }
        }
        return 'hindu';
    }

    /**
     * Keywords to match community_name to festival sets
     */
    private static function communityKeywords(): array
    {
        return [
            'marathi'   => ['marathi', 'maharashtrian', 'maratha'],
            'gujarati'  => ['gujarati', 'gujrati'],
            'tamil'     => ['tamil', 'tamilian', 'iyer', 'iyengar'],
            'bengali'   => ['bengali', 'bangla', 'bong'],
            'punjabi'   => ['punjabi', 'sikh'],
            'south'     => ['south indian', 'kerala', 'malayali', 'kannada', 'karnataka'],
            'telugu'    => ['telugu', 'andhra', 'telangana'],
            'north'     => ['north indian', 'hindi', 'up', 'bihari', 'rajasthani'],
            'odia'      => ['odia', 'odisha', 'orissa'],
        ];
    }

    // ====================================================================
    // STATIC FESTIVAL METADATA (names, icons, significance, prep days)
    // Dates are NOT stored here — they come from AI cache.
    // ====================================================================

    private static function festivalMeta(): array
    {
        return [
            'marathi' => [
                ['name' => 'Gudi Padwa', 'icon' => 'fa-flag', 'significance' => 'Marathi New Year — marks the beginning of Chaitra month and the spring harvest season.', 'preparation_days' => 3],
                ['name' => 'Ram Navami', 'icon' => 'fa-pray', 'significance' => 'Celebrates the birth of Lord Rama. Devotees observe fasts and perform special pujas.', 'preparation_days' => 2],
                ['name' => 'Hanuman Jayanti', 'icon' => 'fa-fist-raised', 'significance' => 'Birth anniversary of Lord Hanuman. Devotees visit temples and recite Hanuman Chalisa.', 'preparation_days' => 1],
                ['name' => 'Vat Pournima', 'icon' => 'fa-tree', 'significance' => 'Married women fast and worship the Banyan tree for the long life and prosperity of their husbands.', 'preparation_days' => 2],
                ['name' => 'Ashadhi Ekadashi', 'icon' => 'fa-om', 'significance' => 'Sacred Ekadashi dedicated to Lord Vitthal. Major pilgrimage to Pandharpur.', 'preparation_days' => 3],
                ['name' => 'Nag Panchami', 'icon' => 'fa-dragon', 'significance' => 'Worship of serpent gods (Nagas). Offerings of milk and turmeric at snake idols.', 'preparation_days' => 1],
                ['name' => 'Ganesh Chaturthi', 'icon' => 'fa-om', 'significance' => 'Grand 10-day festival celebrating Lord Ganesha. Clay idol installation, modak, aarti, and visarjan.', 'preparation_days' => 7],
                ['name' => 'Navratri', 'icon' => 'fa-fire', 'significance' => 'Nine nights of Goddess Durga worship. Ghatasthapana, garba, and fasting.', 'preparation_days' => 3],
                ['name' => 'Diwali', 'icon' => 'fa-fire-alt', 'significance' => 'Festival of lights — Lakshmi puja, rangoli, diyas, and family celebrations.', 'preparation_days' => 5],
            ],

            'gujarati' => [
                ['name' => 'Ram Navami', 'icon' => 'fa-pray', 'significance' => 'Celebrates the birth of Lord Rama with temple processions and pujas.', 'preparation_days' => 2],
                ['name' => 'Rath Yatra', 'icon' => 'fa-cart-arrow-down', 'significance' => 'Grand chariot procession of Lord Jagannath through the city streets.', 'preparation_days' => 2],
                ['name' => 'Janmashtami', 'icon' => 'fa-baby', 'significance' => 'Birth of Lord Krishna. Midnight celebration, dahi handi, and devotional songs.', 'preparation_days' => 2],
                ['name' => 'Navratri (Garba)', 'icon' => 'fa-music', 'significance' => 'Nine nights of Garba and Dandiya Raas. The biggest Gujarati festival celebrating Goddess Amba.', 'preparation_days' => 5],
                ['name' => 'Dussehra', 'icon' => 'fa-shield-alt', 'significance' => 'Victory of Lord Rama over Ravana. Fafda-jalebi breakfast tradition in Gujarat.', 'preparation_days' => 1],
                ['name' => 'Diwali', 'icon' => 'fa-fire-alt', 'significance' => 'Festival of lights and Gujarati New Year (Bestu Varas the next day). Chopda Pujan for businesses.', 'preparation_days' => 5],
                ['name' => 'Uttarayan (Makar Sankranti)', 'icon' => 'fa-wind', 'significance' => 'Kite flying festival marking the transition of the sun into Capricorn.', 'preparation_days' => 3],
            ],

            'tamil' => [
                ['name' => 'Puthandu (Tamil New Year)', 'icon' => 'fa-calendar-day', 'significance' => 'Tamil New Year. Families prepare mango pachadi symbolizing life\'s different flavors.', 'preparation_days' => 2],
                ['name' => 'Aadi Perukku', 'icon' => 'fa-water', 'significance' => 'Celebration of river water rising. Thanks to water bodies for agricultural prosperity.', 'preparation_days' => 1],
                ['name' => 'Vinayaka Chaturthi', 'icon' => 'fa-om', 'significance' => 'Worship of Lord Ganesha with modak, kozhukattai, and special pujas.', 'preparation_days' => 2],
                ['name' => 'Navratri (Golu)', 'icon' => 'fa-chess-queen', 'significance' => 'Display of Golu dolls, sundal preparation, and evening bhajans for nine nights.', 'preparation_days' => 5],
                ['name' => 'Deepavali', 'icon' => 'fa-fire-alt', 'significance' => 'Festival of lights — early morning oil bath, new clothes, crackers, and Lakshmi puja.', 'preparation_days' => 3],
                ['name' => 'Karthigai Deepam', 'icon' => 'fa-fire', 'significance' => 'Festival of lamps — homes and temples are lit with rows of oil lamps.', 'preparation_days' => 2],
                ['name' => 'Thai Pongal', 'icon' => 'fa-sun', 'significance' => 'Harvest festival — boiling rice in new pots as offerings to Surya (Sun God).', 'preparation_days' => 3],
            ],

            'bengali' => [
                ['name' => 'Poila Boishakh (Bengali New Year)', 'icon' => 'fa-calendar-day', 'significance' => 'Bengali New Year. Halkhata (new accounts), sweets, and cultural programs.', 'preparation_days' => 2],
                ['name' => 'Rath Yatra', 'icon' => 'fa-cart-arrow-down', 'significance' => 'Lord Jagannath chariot procession — major celebration in Kolkata and Puri.', 'preparation_days' => 2],
                ['name' => 'Janmashtami', 'icon' => 'fa-baby', 'significance' => 'Birth of Lord Krishna. Midnight celebrations, devotional singing, and fasting.', 'preparation_days' => 2],
                ['name' => 'Durga Puja', 'icon' => 'fa-crown', 'significance' => 'The biggest Bengali festival — 5 days of Goddess Durga worship, dhunuchi naach, and sindoor khela.', 'preparation_days' => 7],
                ['name' => 'Lakshmi Puja', 'icon' => 'fa-coins', 'significance' => 'Worship of Goddess Lakshmi for wealth and prosperity on the full moon after Durga Puja.', 'preparation_days' => 2],
                ['name' => 'Kali Puja', 'icon' => 'fa-fire-alt', 'significance' => 'Worship of Goddess Kali on Diwali night — tantric rituals and temple celebrations.', 'preparation_days' => 2],
                ['name' => 'Saraswati Puja', 'icon' => 'fa-book', 'significance' => 'Worship of Goddess Saraswati for knowledge. Students place books before the idol.', 'preparation_days' => 2],
            ],

            'punjabi' => [
                ['name' => 'Baisakhi', 'icon' => 'fa-seedling', 'significance' => 'Punjabi New Year and harvest festival. Bhangra, langars, and nagar kirtan processions.', 'preparation_days' => 3],
                ['name' => 'Raksha Bandhan', 'icon' => 'fa-heart', 'significance' => 'Sisters tie rakhi on brothers\' wrists. Gift exchange and family celebrations.', 'preparation_days' => 2],
                ['name' => 'Janmashtami', 'icon' => 'fa-baby', 'significance' => 'Birth of Lord Krishna. Dahi handi, midnight prayers, and devotional songs.', 'preparation_days' => 2],
                ['name' => 'Karva Chauth', 'icon' => 'fa-moon', 'significance' => 'Married women observe a strict fast for husbands\' longevity until moonrise.', 'preparation_days' => 2],
                ['name' => 'Diwali', 'icon' => 'fa-fire-alt', 'significance' => 'Festival of lights — Lakshmi puja, fireworks, sweets, and family gatherings.', 'preparation_days' => 5],
                ['name' => 'Lohri', 'icon' => 'fa-fire', 'significance' => 'Bonfire festival celebrating the end of winter. Peanuts, popcorn, and gajjak.', 'preparation_days' => 2],
            ],

            'telugu' => [
                ['name' => 'Ugadi (Telugu New Year)', 'icon' => 'fa-calendar-day', 'significance' => 'Telugu New Year — pachadi with six flavors representing life\'s experiences.', 'preparation_days' => 2],
                ['name' => 'Sri Rama Navami', 'icon' => 'fa-pray', 'significance' => 'Birth of Lord Rama. Kalyanam (celestial wedding) celebrations in temples.', 'preparation_days' => 2],
                ['name' => 'Vinayaka Chavithi', 'icon' => 'fa-om', 'significance' => 'Grand festival of Lord Ganesha — clay idol installation, modak, and visarjan.', 'preparation_days' => 3],
                ['name' => 'Bathukamma', 'icon' => 'fa-spa', 'significance' => 'Telangana floral festival — women make flower arrangements and dance in circles.', 'preparation_days' => 3],
                ['name' => 'Dasara', 'icon' => 'fa-shield-alt', 'significance' => 'Victory of good over evil. Shami vruksha puja and weapon worship.', 'preparation_days' => 2],
                ['name' => 'Deepavali', 'icon' => 'fa-fire-alt', 'significance' => 'Festival of lights — oil bath, new clothes, firecrackers, and sweets.', 'preparation_days' => 3],
                ['name' => 'Sankranti', 'icon' => 'fa-sun', 'significance' => 'Harvest festival — Bhogi, Sankranti, Kanuma. Rangoli, kite flying, and bonfires.', 'preparation_days' => 3],
            ],

            'south' => [
                ['name' => 'Ugadi', 'icon' => 'fa-calendar-day', 'significance' => 'South Indian New Year with traditional prasadam and panchanga shravanam.', 'preparation_days' => 2],
                ['name' => 'Vishu', 'icon' => 'fa-eye', 'significance' => 'Vishukkani — auspicious first sight of the year with mirror, fruits, and gold.', 'preparation_days' => 2],
                ['name' => 'Onam', 'icon' => 'fa-leaf', 'significance' => 'Kerala harvest festival — elaborate Onam Sadhya (feast), Pookalam, and Vallam Kali.', 'preparation_days' => 5],
                ['name' => 'Navratri', 'icon' => 'fa-chess-queen', 'significance' => 'Display of dolls on steps, sundal distribution, and evening bhajans.', 'preparation_days' => 3],
                ['name' => 'Deepavali', 'icon' => 'fa-fire-alt', 'significance' => 'Festival of lights — oil bath, new clothes, and Lakshmi/Ganesha puja.', 'preparation_days' => 3],
                ['name' => 'Karthigai Deepam', 'icon' => 'fa-fire', 'significance' => 'Rows of oil lamps lit in homes and temples. Tiruvannamalai Maha Deepam.', 'preparation_days' => 2],
                ['name' => 'Pongal', 'icon' => 'fa-sun', 'significance' => 'Harvest festival — new rice boiled in pots as offering to the Sun God.', 'preparation_days' => 3],
            ],

            'north' => [
                ['name' => 'Chaitra Navratri', 'icon' => 'fa-fire', 'significance' => 'Nine-day spring Navratri — Ghatasthapana, Goddess Durga worship, and fasting.', 'preparation_days' => 2],
                ['name' => 'Ram Navami', 'icon' => 'fa-pray', 'significance' => 'Birth of Lord Rama. Ramayana recitation, fasting, and temple visits.', 'preparation_days' => 2],
                ['name' => 'Raksha Bandhan', 'icon' => 'fa-heart', 'significance' => 'Sisters tie rakhi on brothers\' wrists celebrating sibling love.', 'preparation_days' => 2],
                ['name' => 'Janmashtami', 'icon' => 'fa-baby', 'significance' => 'Birth of Lord Krishna. Midnight worship, dahi handi, and bhajans.', 'preparation_days' => 2],
                ['name' => 'Sharad Navratri', 'icon' => 'fa-fire', 'significance' => 'Nine nights of Goddess Durga worship — fasting, havan, and Durga puja.', 'preparation_days' => 3],
                ['name' => 'Dussehra', 'icon' => 'fa-shield-alt', 'significance' => 'Victory of Rama over Ravana. Ravan dahan and Ram Lila performances.', 'preparation_days' => 2],
                ['name' => 'Karva Chauth', 'icon' => 'fa-moon', 'significance' => 'Married women fast for husbands\' longevity until moonrise.', 'preparation_days' => 2],
                ['name' => 'Diwali', 'icon' => 'fa-fire-alt', 'significance' => 'Festival of lights — Lakshmi puja, diyas, rangoli, and fireworks.', 'preparation_days' => 5],
                ['name' => 'Chhath Puja', 'icon' => 'fa-sun', 'significance' => 'Ancient Vedic festival worshipping Surya. Standing in water and offering arghya.', 'preparation_days' => 3],
                ['name' => 'Makar Sankranti', 'icon' => 'fa-sun', 'significance' => 'Harvest festival — til laddu, kite flying, and holy river dips.', 'preparation_days' => 2],
            ],

            'odia' => [
                ['name' => 'Pana Sankranti (Odia New Year)', 'icon' => 'fa-calendar-day', 'significance' => 'Odia New Year — preparation of Pana (sweetened drink) offered to Lord Hanuman.', 'preparation_days' => 2],
                ['name' => 'Raja Parba', 'icon' => 'fa-seedling', 'significance' => '3-day celebration of womanhood and Earth. Swings, pitha, and games.', 'preparation_days' => 2],
                ['name' => 'Rath Yatra', 'icon' => 'fa-cart-arrow-down', 'significance' => 'Grand chariot festival of Lord Jagannath at Puri — one of India\'s biggest celebrations.', 'preparation_days' => 5],
                ['name' => 'Ganesh Puja', 'icon' => 'fa-om', 'significance' => 'Lord Ganesha worship with modak and community pandal celebrations.', 'preparation_days' => 2],
                ['name' => 'Durga Puja', 'icon' => 'fa-crown', 'significance' => 'Grand worship of Goddess Durga with elaborate pandals and community feasts.', 'preparation_days' => 5],
                ['name' => 'Diwali', 'icon' => 'fa-fire-alt', 'significance' => 'Festival of lights — Kali puja and Lakshmi puja traditions.', 'preparation_days' => 3],
            ],

            'hindu' => [
                ['name' => 'Chaitra Navratri', 'icon' => 'fa-fire', 'significance' => 'Nine-day spring Navratri — Ghatasthapana, fasting, and Goddess Durga worship.', 'preparation_days' => 2],
                ['name' => 'Ram Navami', 'icon' => 'fa-pray', 'significance' => 'Celebrates the birth of Lord Rama with fasting and temple visits.', 'preparation_days' => 2],
                ['name' => 'Raksha Bandhan', 'icon' => 'fa-heart', 'significance' => 'Celebrates the bond between siblings with rakhi tying ceremony.', 'preparation_days' => 2],
                ['name' => 'Janmashtami', 'icon' => 'fa-baby', 'significance' => 'Birth of Lord Krishna. Midnight worship, fasting, and dahi handi.', 'preparation_days' => 2],
                ['name' => 'Ganesh Chaturthi', 'icon' => 'fa-om', 'significance' => 'Grand festival celebrating Lord Ganesha with idol installation and visarjan.', 'preparation_days' => 3],
                ['name' => 'Sharad Navratri', 'icon' => 'fa-fire', 'significance' => 'Nine nights of Goddess Durga worship with fasting, garba, and puja.', 'preparation_days' => 3],
                ['name' => 'Dussehra', 'icon' => 'fa-shield-alt', 'significance' => 'Victory of Rama over Ravana. Weapon puja and Ravan dahan.', 'preparation_days' => 2],
                ['name' => 'Diwali', 'icon' => 'fa-fire-alt', 'significance' => 'Festival of lights — Lakshmi puja, diyas, rangoli, and fireworks.', 'preparation_days' => 5],
                ['name' => 'Makar Sankranti', 'icon' => 'fa-sun', 'significance' => 'Harvest festival marking the sun\'s northward journey. Til and jaggery sweets.', 'preparation_days' => 2],
            ],
        ];
    }
}
